apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: scaledown
spec:
  postgresVersion: ${KUTTL_PG_VERSION}
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          encryption_key_command: 'echo 0aa19145816bd81a8371a725ef223900'
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
